# syntax=docker/dockerfile:1
FROM node:12.18.1 as builder
WORKDIR '/app'
COPY ["package.json", "package-lock.json*", "./"]
RUN npm install --production
COPY . . 
RUN npm run build
FROM nginx:latest
COPY --from=builder /app/build /usr/share/nginx/html
